<?php
/* @var $model CompanyListingAgreement */
$f = Yii::app()->format;
?>
<h4>TERMS AND CONDITIONS TO WORK ON COMPANY LISTINGS</h4>

<ul>
	<li>All property listings or sales leads that are generated and/or assigned to you by the Company shall be classified as the Company listings.</li> 
	<li>All property listings that are from your personal contact or source shall be classified as Individual listings.</li>
</ul>

<p>I agree to pay the Company a referral fee of twenty percent (20%) of the total commission received from the transaction generated by the Company listings.  The balance of the eighty percent (80%) of the commission is subjected to the commission scheme stated in the Associate Agreement with the Company.</p>


<h4>TERMS OF RENEWAL FOR RENTAL LISTINGS</h4>  

<ul>
	<li>If the rental properties from the Company listings are sold by you, such transactions shall remain as Company listings.</li>

	<li>If the rental listings are renewed or extended for further terms, the commission paid for the renewal is subjected to Company listings.</li>

	<li>If the property owner(s) from the Company listings provide you with new rental listings and/or sales leads, such leads shall be considered as new listings and shall remain as Individual listings.</li> 

	<li>In the event that you terminate your employment with the Company, commission shall not be payable to you on all renewals and/or extension of lease from the Company listings.</li>
</ul>

<p>I agree and understood the terms of renewal for rental listings.</p>

<h4>NON-DISCLOSURE</h4>

<ul>
	<li>Client information e.g. the clients’ contact/property details from the Company listings shall be kept Private & Confidential and shall not be disclosed to any third-party at all times.</li>

	<li>The Associates shall not contact the clients from the Company listings and also be required to return all information relating to the Company listings in the event of termination of employment with the Company.</li>
</ul>

<p>I agree to abide the duties of the Non-disclosure clause. </p>

<p>PREFERED CHOICES  (DISTRICT NO.)</p>

<table>
	<tr>
		<th style="width: 80px">1 <sup>ST</sup></th>
		<td><?= $f->formatEnum($model->location_id_1, ProLocation::getListDataLocation()) ?></td>
	</tr>
	<tr>
		<th>2 <sup>ND</sup></th>
		<td><?= $f->formatEnum($model->location_id_2, ProLocation::getListDataLocation()) ?></td>
	</tr>
	<tr>
		<th>3 <sup>RD</sup></th>
		<td><?= $f->formatEnum($model->location_id_3, ProLocation::getListDataLocation()) ?></td>
	</tr>
</table>
